### ISSUE TITLE
Can't use a video url from a YouTube playlist

### ISSUE THREAD

**Issue by r-patton** [rsikdar/VSync#5]
The same video will have a different url when it's viewed in context of its playlist and then cannot be loaded by putting that in the search bar.

**Comment by rsikdar** [comment]
This works fine for me actually. The version on the server had an issue that any youtube link entered on the main page wouldn't work as I forgot to change it to redirect to vroom.html instead of the old cards.html. This is now fixed and pushed to the server. Let me know if you still have the issue.
